output {

  # Chỉ gửi tin nhắn nếu log đó được xác định là một cuộc tấn công

  if [attack_type] and "exceeded_limit" not in [tags]{

    http {

      url => "https://api.telegram.org/bot8473734314:AAHXgoJyqFimj18Zkt_55hBas-LyBdR81zI/sendMessage"

      http_method => "post"

      format => "json"

      mapping => {

        "chat_id" => "5898979798"

        "text" => "🚨 CẢNH BÁO TẤN CÔNG WAF 🚨

----------------------------------

🔥 Loại: %{attack_type}

🌐 IP Nguồn: %{[waf][transaction][client_ip]}

🔗 URL: %{[waf][transaction][request][uri]}

🛠 Method: %{[waf][transaction][request][method]}

⏰ Thời gian: %{@timestamp}

----------------------------------"

      }

    }

  }

}
