events {}

http {
    server {
        listen ${PORT};

        location / {
            proxy_pass http://lamp_web:80;  # ⚠️ trỏ tới web container
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
